In [1]:
inputs = [ 1 , 2 , 3 ]
weights = [ 0.2 , 0.8 , - 0.5 ]
bias = 2

In [2]:
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2])+bias
print(output)


2.3


In [3]:
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , - 0.5 , 1.0 ]
bias = 2.0

In [5]:
output=(inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3])+bias
print(output)

4.8


In [1]:
inputs = [ 1 , 2 , 3 , 2.5 ]
weights = [
    [ 0.2 , 0.8 , - 0.5 , 1 ],
    [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
    [ - 0.26 , - 0.27 , 0.17 , 0.87 ]
]
biases = [ 2 , 3 , 0.5 ]
# Output of current layer
layer_outputs = []

for n_biases, neuron_weights in zip(biases,weights):
    output_neuron=0

    for n_inputs, weight in zip(inputs,neuron_weights):
        output_neuron+= n_inputs*weight

    output_neuron+=n_biases    
    layer_outputs.append(output_neuron)

print(layer_outputs)    


[4.8, 1.21, 2.385]


In [3]:
# dot product 

a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]

dot_product=0
for as_elem,bs_elem in zip(a,b):
    dot_product+=as_elem*bs_elem

print(dot_product)    

20


In [6]:
# A single neuron with numpy
import numpy as np
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , - 0.5 , 1.0 ]
bias = 2.0

dot_product=np.dot(inputs,weights)+bias
print(dot_product)

4.8


In [11]:
# A Layer of Neurons with NumPy
import numpy as np
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [
    [ 0.2 , 0.8 , - 0.5 , 1 ],
    [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
    [ - 0.26 , - 0.27 , 0.17 , 0.87 ]
]
biases = [ 2.0 , 3.0 , 0.5 ]

dot_product=np.dot(weights,inputs)+biases
print(dot_product)

[4.8   1.21  2.385]


In [16]:
# row matrix and column matrix 
a=[[1,3,4]]
b=[[1],
   [3],
   [5]]

print(np.dot(a,b))

[[30]]


In [30]:
# Transposition

import numpy as np
a=[1,3,4]
b=[3,2,1]

a=np.array([a])
# transposition
b=np.array([b]).T

dot_product=np.dot(a,b)
print(dot_product)

[[13]]


In [32]:
# A Layer of Neurons & Batch of Data w/ NumPy
import numpy as np
inputs = [
    [ 1.0 , 2.0 , 3.0 , 2.5 ],
    [ 2.0 , 5.0 , - 1.0 , 2.0 ],
    [ - 1.5 , 2.7 , 3.3 , - 0.8 ]
]
weights = [
    [ 0.2 , 0.8 , - 0.5 , 1.0 ],
    [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
    [ - 0.26 , - 0.27 , 0.17 , 0.87 ]
]
biases = [ 2.0 , 3.0 , 0.5 ]

weights=np.array(weights).T #transposition matrixes 
layer_output=np.dot(inputs,weights)+biases
print(layer_output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
